### ISSUE TITLE
[Feature Request] Add docs

### ISSUE THREAD

**Issue by ejcupcake1234alt** [nestriness/nestri#102]
I have made a wiki for nestri. Can you please add it when you have time? GitHub doesn't let you put a wiki in a pull request.
[https://github.com/ejcupcake1234alt/nestri/wiki](https://github.com/ejcupcake1234alt/nestri/wiki)

**Comment by wanjohiryan** [comment]
Hello there  @ejcupcake1234alt 👋🏾

This is good, thank you.

I was thinking of using a docs website for this instead. 

I have yet to look into this tho, but there is a specific directory for this in the mono-repo [here](https://github.com/nestriness/nestri/tree/main/apps/docs). 

I might migrate it to Astro tho, NextJS has pretty bad Developer Xperience on non-Vercel platforms.

Let me open a PR immediately.

**Comment by wanjohiryan** [comment]
This has been closed by #116
