### ISSUE TITLE
🎥 [Feature Request] Request for a Demo Video

### ISSUE THREAD

**Issue by vithalreddy** [nestriness/nestri#47]
Firstly, I want to thank you for your incredible work. It’s an impressive project.

can you add an short video showcasing a live demo? it will help the users to make decision on buying pro plan.

I understand it's an experimental software, but still it would benefit the community.

Thanks :)

**Comment by wanjohiryan** [comment]
Thank you so much for your kind words and support! 🌟

You've made a fantastic suggestion. A short video demo will indeed be a powerful tool to help potential users understand the value of our Pro plan. I’ll work on setting up a video asap, so please keep an eye out for that.

Additionally, we’re excited to announce a Demo Day happening next week! It’s a perfect opportunity to see our project in action and ask any questions you might have. For more details and to stay updated, I invite you to join our [Discord server](https://discord.com/invite/Y6etn3qKZ3)

Looking forward to seeing you there!

**Comment by wanjohiryan** [comment]
Hey, took me a while but we have a minor "demo video" on the README... 

Closing this as completed :D
