### ISSUE TITLE
🛡️ [Branding] Potential Trademark Issues

### ISSUE THREAD

**Issue by kevin-wijnen** [nestriness/nestri#48]
# Issue

Hi there, congratulations on this FOSS project. 👏 I stumbled upon this project on social media, cool to see someone tackling a selfhostable GeForce NOW.

However, after looking at the project I spotted potential issues with the project's branding:

## Potential legal issue

While I am not an attorney or lawyer in any way, shape or form, I did notice Google's Stadia logo being present on the "overview banner" in the `README.md`. Despite [the clear disassociation on the website](https://netris.me/#:~:text=however%2C%20it's%20important%20to%20note%20that%20while%20we've%20drawn%20inspiration%20from%20stadia%2C%20we%20operate%20completely%20independently%20with%20no%20ties%20to%20stadia%20or%20google.), I don't think it's legal to use their trademarked logo as advertising unless you actually use Stadia's technology. (Compared to using Steam's and NVIDIA's trademarks as the project utilises Steam as software, and NVIDIA both in software and hardware, making that usage more so "fair use".)

## General name confusion/unclarity

The name Netris has several issues regarding clarity:

- Name is confusing, sounding either like a TETRIS clone or some type of network tool (other than "game streaming").
- Several preexisting projects on GitHub [share the same name](https://github.com/search?q=netris&type=repositories), not helping beating the confusion of the name. Not to mention other companies or software projects globally using the name already (a quick Google search will show up [Netris VPC](https://www.netris.io/) for example).

# Proposal

I would suggest to quickly remove the Stadia trademark from the banner in the `README.md` to not attract any potential legal action from Google, especially as this could be seen as a "threatening competitor" to their (now defunct towards the general public) streaming service. 

Another suggestion would be to rename the project, although I do understand that would be a bit more difficult as that would require renaming Netris everywhere.

**Comment by wanjohiryan** [comment]
Hey @kevin-wijnen 

Thank you so much for bringing this to our attention! We'll remove the Stadia logo from our banner as soon as possible. It's clear we overlooked the potential implications of using it, and your insight here is greatly appreciated.

Regarding the project's name, you've raised some valid points about potential confusion. While it's true that different entities can share the same name without issue in non-competing sectors, your concerns about clarity and uniqueness are well noted. We'll take a closer look at how our project name might be perceived and consider the possibility of a rename to avoid any confusion and ensure our project stands out.

Your expertise and feedback in this area are invaluable to us. Thank you again for taking the time to share your thoughts.

**Comment by wanjohiryan** [comment]
For reference: we just got a trademark violation email from youknowho... damn!

@kevin-wijnen this is probably a stretch, but do you have any good names (with a domain) for a cloud gaming service?

**Comment by wanjohiryan** [comment]
We renamed to `Nestri` and even got a new domain name, and brand colors...

Maybe it is time to close this as completed
