### ISSUE TITLE
[🐛 Bug] Enigo causes gamescope to quit

### ISSUE THREAD

**Issue by wanjohiryan** [nestriness/nestri#67]
I am getting an error, whereby, if the `warp-input` server is connected to the frontend, and running `/usr/games/gamescope` cannot start. 

The error i get is:
```bash
netris@f303b471529c:~$ /usr/games/gamescope -- vkcube
wlserver: [backend/headless/backend.c:68] Creating headless backend
gamescope: ../src/wlserver.cpp:1413: void wlserver_key(uint32_t, bool, uint32_t): Assertion `wlserver.wlr.virtual_keyboard_device != nullptr' failed.
Aborted
```

And after disconnecting from the input session, you get:
```bash
wlserver: [wayland] error: XDG_RUNTIME_DIR is invalid or not set in the environment
```

You have to ait long enough for the `warp-input` server to go into the "retry loop" before you can start gamescope.

**Comment by djpremier** [comment]
Hi @wanjohiryan,

For reference:
https://github.com/ValveSoftware/gamescope/issues/661
https://github.com/ValveSoftware/gamescope/issues/497

**Comment by wanjohiryan** [comment]
Hi @wanjohiryan 

Those are really nice references. From your link[1] I believe it has to be something to do with gamescope cannot "read" the fake keyboard and mouse input from enigo. 

So, a patch would be to kill `warp-input` each time gamescope is called. Or figure out how to run it in privileged mode.

**Comment by wanjohiryan** [comment]
We moved away from `enigo` and `gamescope` on the latest release...

Closing this as `wont-fix`
