### ISSUE TITLE
[🐛 Bug] Error, no command specified to run the game. Exiting.

### ISSUE THREAD

**Issue by dgudim** [nestriness/nestri#72]
Following the step-by-step guide I can't get it to start.
Doing `/etc/startup.sh > /dev/null &` never produces .X11-unix in tmp. 

Running it without `&` gives the following message: `Error, no command specified to run the game. Exiting.`

**Comment by hraphael** [comment]
I have the same problem and running it with `/etc/startup.sh netris-proton -wr <game>.exe` does seems to work but the script is then stuck in a loop where it tries to install winehq. Running it with `-pr` noes not work because proton is not installed.

**Comment by suchipi** [comment]
I can't get it to work, either. It definitely seems you have to pass the game command directly to `/etc/startup.sh` rather than waiting for `.X11-unix` as the readme says, but no matter what game I give it, it crashes. I installed `xterm` into the container to try to run it with something small, but that crashes, too. The log output in /tmp says:
```
xterm: Xt error: Can't open display: :0
```

It's worth mentioning that the readme said to set up nvidia-docker, but the [nvidia-docker repo](https://github.com/NVIDIA/nvidia-docker) says it's been deprecated and replaced with nvidia container toolkit, so I installed and set up that instead of `nvidia-docker`.

**Comment by wanjohiryan** [comment]
Hey, this has been fixed by #73

**Comment by wanjohiryan** [comment]
@suchipi it seems like your Xterm error might be unrelated to the startup.sh, can you give more details.

Try docker pulling the latest server image like so:


>docker pull ghcr.io/netrisdotme/netris/server:nightly

Then try running again. Tell us if you get the Xterm error again.

**Comment by dgudim** [comment]
The previous issue is fixed now, it seems to startup, but wine and proton just die instantly ad the game does not start. 

Here is my attempt to start it
[out.webm](https://github.com/netrisdotme/netris/assets/34401005/9ffaadf3-841b-426a-a907-60539fff7241)

Here are the logs
[entrypoint-stdout---supervisor-_be6c0w1.log](https://github.com/user-attachments/files/15521396/entrypoint-stdout---supervisor-_be6c0w1.log)
[game-stdout---supervisor-wd2ccmr9.log](https://github.com/user-attachments/files/15521397/game-stdout---supervisor-wd2ccmr9.log)
[supervisord.log](https://github.com/user-attachments/files/15521398/supervisord.log)

**Comment by wanjohiryan** [comment]
Hey @dgudim 

Thank you so much for the video, this is the most comprehensive feedback anyone has given so far. From the video, I can tell that wine has trouble getting a display to draw its dialog on, which means that Xorg is not working for some reason. From the `entrypoint.log` file I can see that X11 shows errors there too. Confirming my suspicion(s).

However, this raises the question, how comes the X11 unix socket is present?

Also, from the entrypoint logs, 
```bash
Fatal server error:
(EE) no screens found(EE) 
(EE) 
```

I have seen this error before, but I cannot remember what I did to solve it.

@ehfd what do you think?

**Comment by dgudim** [comment]
If I can help you with debugging, I'll do what I can

> Oh, and what tool did you use to record your terminal @dgudim ? Thanks :)

asciinema (https://github.com/asciinema/asciinema)

**Comment by ehfd** [comment]
You need to clear all junk files which are supposed to lock the state of the screen and restart again. For more information, you need the Xorg.0.log.

**Comment by dgudim** [comment]
Sorry for the delay, I almost got this working. The steps I took are as follows:
1. Set default target of systemd to multiuser (instead of loading into graphical and then shutting down xorg)
2. Disabled nvidia drm fbdev kernel option (nvidia_drm.fbdev=1)
3. Switched to using root docker instead of rootless and turned on cgroups in the nvidia container toolkit (they should be disabled when running in rootless)

Now everything seems to start normally and doesn't die. But upon loading the website I get a black screen and a CORS error

![image](https://github.com/netrisdotme/netris/assets/34401005/7947863e-b59e-4331-aa6a-1f3c03257d0f)

![image](https://github.com/netrisdotme/netris/assets/34401005/f8b2f85e-e6a1-4b23-8a95-c5ac0eb526ca)

**Comment by dgudim** [comment]
Adding the header with header modifier extension worked as a temporary solution. Now I get this 
![image](https://github.com/netrisdotme/netris/assets/34401005/0da16af5-a0ec-4b8d-a701-fb43651910e8)
However, the cursor is not captured so I am not able to do anything

**Comment by wanjohiryan** [comment]
The headers are now fixed... you should be able to play without requiring the extension.

As for the cursor, are you getting any "announce_error" logs on your console? If so, reload the page. It should fix that.

**Comment by dgudim** [comment]
Hey. 
> For the CrossOrigin Isolation header, they are now fixed

Nice! It works here

> As for the cursor, are you getting any `announce_error`
No, but I am getting `Uncaught (in promise) DOMException: The options asked for in this request are not supported on this platform` when I click on the screen, I am trying from linux, don't know about windows, don't have any windows machines

**Comment by dgudim** [comment]
Seems like it's related to this piece of code, but I am not sure
```js
    const [u] = ct();
    u.value && (await u.value.requestFullscreen(),
    u.value.requestPointerLock({
        unadjustedMovement: !0
    }))
```

**Comment by wanjohiryan** [comment]
Thank you for the info @dgudim it seems like ``adjustMovement`` has an issue on Linux. Could you please write your system information on this open issue #77
