### ISSUE TITLE
[🐛 Bug] Mouse Pointer is not locked

### ISSUE THREAD

**Issue by AquaWolf** [nestriness/nestri#77]
Description:
For some Chrome clients the mouse is not locked to the netris web interface. So that the mousepointer cannot be moved in the Chrome fullscreen window.

### **Information:**
**Operating System:**
Fedora Linux 40 (Workstation Edition)
**Chrome Version:**
Version 125.0.6422.141 (Offizieller Build) (64-Bit)

**Comment by Pegoku** [comment]
**Operating System:**
Ubuntu 22.04 LTS
**Browser Version:**
Brave: Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) unknown (64-bit)

**Comment by DatCaptainHorse** [comment]
**Operating System:**
openSUSE Tumbleweed 20240531
**Browser Version:**
Vivaldi 6.7.3329.39 (Chrome/124.0.0.0)

**Comment by noideaman** [comment]
**Operating System:**
Garuda (Arch) Gnome (both x11 and wayland)
**Browser Version:**
Chrome Version 126.0.6478.55
Chromium Version 126.0.6478.55 

**Operating System:**
Windows 11 23H2 (Build 22631.3593)
**Browser Version:**
Chromium Version 125.0.6422.142

**Comment by dgudim** [comment]
**Operating System**:
Arch KDE (both x11 and wayland)
**Browser Version**:
Google Chrome Version 126.0.6478.61
